name: Deploy to HF
on:
  push:
    branches: [main]

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Push to HF
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: git push https://bushra-siraj:$HF_TOKEN@huggingface.co/spaces/bushra-siraj/stock-fund-analyzer main
